#ifndef __ERRORCODELIST_H
#define __ERRORCODELIST_H

enum class ErrorCode
{
	//0-99 - General - prefix: "G_"
	G_OK						= 0,
	G_FAIL						= 1,
	G_GLYPH_COULD_NOT_BE_LOADED	= 2,
	G_INVALID_ARGUMENT			= 3,
	//100-199 - Linux General - prefix: "LG"

	//200-299 - Windows General - prefix: "WG"

	//300-399 - Linux sub - prefix: "L*" *=whatever the sub is called
	LGFX_OK		= 200,
	LGFX_FAIL	= 201,
		
	//300-399 - Windows sub - prefix: "W*" *=whatever the sub is called
	WGFX_OK								= G_OK,
	WGFX_FAIL							= 201,
	WGFX_BUFFER_INIT_FAIL				= 202,
	WGFX_BUFFER_INIT_OK					= G_OK,
	WGFX_TEXTURE_INIT_FAIL				= 203,
	WGFX_TEXTURE_INIT_OK				= G_OK,
	WGFX_CREATE_SWAPCHAIN_FAIL			= 204,
	WGFX_GET_SWAPCHAIN_BUFFER_FAIL		= 205,
	WGFX_CREATE_RENDERTARGET_FAIL		= 206,
	WGFX_SET_SWAPCHAIN_OK				= G_OK,
	WGFX_SETVIEWPORT_OK					= G_OK,
	WGFX_CREATE_RASTERIZER_FAIL			= 207,
	WGFX_CREATE_DEPTHBUFFER_FAIL		= 208,
	WGFX_SET_DEPTHBUFFER_OK				= G_OK,
	WGFX_CREATE_DEPTHSTENCILSTATE_FAIL	= 209,
	WGFX_CREATE_DEPTHSTENCILVIEW_FAIL	= 210,
	WGFX_SET_DEPTHSTENCIL_OK			= G_OK,
	WGFX_SETUP_DXGI_FAIL				= 211,
	WGFX_COMPILE_VS_FAIL				= 212,
	WGFX_COMPILE_PS_FAIL				= 213,
	WGFX_COMPILE_GS_FAIL				= 214,
	WGFX_CREATE_VS_FAIL					= 215,
	WGFX_CREATE_PS_FAIL					= 216,
	WGFX_CREATE_GS_FAIL					= 217,
	WGFX_CREATE_INPUT_LAYOUT_FAIL		= 218,
	WGFX_CREATE_CBUFFER_FAIL			= 219,
	WGFX_CREATE_SAMPLERSTATE_FAIL		= 220,
	WGFX_CREATE_BLENDSTATE_FAIL			= 221,
	WGFX_INITSHADER_OK					= G_OK,
	WGFX_SET_SHADER_PARAMETERS_FAIL		= 222,
	WGFX_SET_SHADER_PARAMETERS_OK		= G_OK,
	WGFX_DRAW_OK						= G_OK,
	WGFX_D3D_INIT_OK					= G_OK,
	WGFX_CREATE_DXGI_FACTORY_FAIL		= 223,
	WGFX_GET_ADAPTER_FAIL				= 224,
	WGFX_ENUMERATE_ADAPTERS_FAIL		= 225,
	WGFX_CREATE_DISPLAY_MODE_LIST_FAIL	= 226,
	WGFX_FILL_DISPLAY_MODE_LIST_FAIL	= 227,
	WGFX_GET_DISPLAY_MODE_DESC_FAIL		= 228,
	WGFX_GET_GPU_DESCRIPTION_FAIL		= 229,
	WGFX_SET_DXGI_OK					= G_OK,
	
};

#endif